export const gameData = [
//   {
//     "id":"SL-FISH",
//     "matrix":{
//        "x":5,
//        "y":3
//     },
//     "linesApiData":[
//        [
//           1,
//           1,
//           1,
//           1,
//           1
//        ],
//        [
//           2,
//           2,
//           2,
//           2,
//           2
//        ],
//        [
//           2,
//           1,
//           0,
//           1,
//           2
//        ],
//        [
//           0,
//           0,
//           1,
//           0,
//           0
//        ],
//        [
//           1,
//           0,
//           0,
//           0,
//           1
//        ],
//        [
//           0,
//           0,
//           0,
//           0,
//           0
//        ],
//        [
//           0,
//           1,
//           2,
//           1,
//           0
//        ],
//        [
//           2,
//           2,
//           1,
//           2,
//           2
//        ],
//        [
//           1,
//           2,
//           2,
//           2,
//           1
//        ],
//        [
//           2,
//           2,
//           1,
//           0,
//           0
//        ],
//        [
//           1,
//           2,
//           1,
//           0,
//           1
//        ],
//        [
//           1,
//           0,
//           1,
//           2,
//           1
//        ]
//     ],
//     "linesCount":[
//        1,
//        2,
//        3,
//        4,
//        5,
//        6,
//        7,
//        8,
//        9,
//        10,
//        11,
//        12
//     ],
//     "bets":[
//        0.1,
//        0.25,
//        0.5,
//        0.75,
//        1
//     ],
//     "bonus":{
//        "type":"tap",
//        "isEnabled":true,
//        "noOfItem":5,
//        "payOut":[
//           25,
//           20,
//           10,
//           5,
//           0
//        ],
//        "payOutProb":[
          
//        ]
//     },
//     "gamble":{
//        "type":"card",
//        "isEnabled":false
//     },
//     "Symbols":[
//        {
//           "Name":"0",
//           "Id":0,
//           "reelInstance":{
//              "0":9,
//              "1":9,
//              "2":9,
//              "3":9,
//              "4":9
//           },
//           "useWildSub":true,
//           "multiplier":[
//              [
//                 100,
//                 0
//              ],
//              [
//                 50,
//                 0
//              ],
//              [
//                 20,
//                 0
//              ]
//           ]
//        },
//        {
//           "Name":"1",
//           "Id":1,
//           "reelInstance":{
//              "0":9,
//              "1":9,
//              "2":9,
//              "3":9,
//              "4":9
//           },
//           "useWildSub":true,
//           "multiplier":[
//              [
//                 100,
//                 0
//              ],
//              [
//                 50,
//                 0
//              ],
//              [
//                 20,
//                 0
//              ]
//           ]
//        },
//        {
//           "Name":"2",
//           "Id":2,
//           "reelInstance":{
//              "0":9,
//              "1":9,
//              "2":9,
//              "3":9,
//              "4":9
//           },
//           "useWildSub":true,
//           "multiplier":[
//              [
//                 100,
//                 0
//              ],
//              [
//                 50,
//                 0
//              ],
//              [
//                 20,
//                 0
//              ]
//           ]
//        },
//        {
//           "Name":"3",
//           "Id":3,
//           "reelInstance":{
//              "0":9,
//              "1":9,
//              "2":9,
//              "3":9,
//              "4":9
//           },
//           "useWildSub":true,
//           "multiplier":[
//              [
//                 100,
//                 0
//              ],
//              [
//                 50,
//                 0
//              ],
//              [
//                 20,
//                 0
//              ]
//           ]
//        },
//        {
//           "Name":"4",
//           "Id":4,
//           "reelInstance":{
//              "0":9,
//              "1":9,
//              "2":9,
//              "3":9,
//              "4":9
//           },
//           "useWildSub":true,
//           "multiplier":[
//              [
//                 100,
//                 0
//              ],
//              [
//                 50,
//                 0
//              ],
//              [
//                 20,
//                 0
//              ]
//           ]
//        },
//        {
//           "Name":"5",
//           "Id":5,
//           "reelInstance":{
//              "0":9,
//              "1":9,
//              "2":9,
//              "3":9,
//              "4":9
//           },
//           "useWildSub":true,
//           "multiplier":[
//              [
//                 100,
//                 0
//              ],
//              [
//                 50,
//                 0
//              ],
//              [
//                 20,
//                 0
//              ]
//           ]
//        },
//        {
//           "Name":"6",
//           "Id":6,
//           "reelInstance":{
//              "0":9,
//              "1":9,
//              "2":9,
//              "3":9,
//              "4":9
//           },
//           "useWildSub":true,
//           "multiplier":[
//              [
//                 100,
//                 0
//              ],
//              [
//                 50,
//                 0
//              ],
//              [
//                 20,
//                 0
//              ]
//           ]
//        },
//        {
//           "Name":"Scatter",
//           "Id":7,
//           "reelInstance":{
//              "0":3,
//              "1":3,
//              "2":3,
//              "3":3,
//              "4":3
//           },
//           "description":"Scatter: Offers higher pay outs when 3 or more symbols appear anywhere on the result matrix. Payout: 5x - 600, 4x - 300, 3x-100",
//           "useWildSub":false,
//           "multiplier":[
//              [
//                 600,
//                 0
//              ],
//              [
//                 300,
//                 0
//              ],
//              [
//                 100,
//                 0
//              ]
//           ]
//        },
//        {
//           "Name":"Bonus",
//           "Id":8,
//           "reelInstance":{
//              "0":3,
//              "1":3,
//              "2":3,
//              "3":3,
//              "4":3
//           },
//           "description":"Starts a Bonus game for a pay out when 3 or more symbols appear anywhere on the result matrix.",
//           "useWildSub":false,
//           "symbolCount":3
//        },
//        {
//           "Name":"Wild",
//           "Id":9,
//           "reelInstance":{
//              "0":2,
//              "1":2,
//              "2":2,
//              "3":2,
//              "4":2
//           },
//           "description":"Substitutes for all symbols except Jackpot, Bonus and Scatter.",
//           "useWildSub":false
//        },
//        {
//           "Name":"Jackpot",
//           "Id":10,
//           "reelInstance":{
//              "0":1,
//              "1":1,
//              "2":1,
//              "3":1,
//              "4":1
//           },
//           "description":"Mega win triggered by 5 Jackpot symbols anywhere on the result matrix. Payout: 5000x",
//           "useWildSub":false,
//           "defaultAmount":5000,
//           "increaseValue":5,
//           "symbolsCount":5
//        }
//     ]
//  }
// {
//   "id":"SL-GF",
//   "matrix":{
//      "x":5,
//      "y":3
//   },
//   "linesApiData":[
//      [
//         1,
//         1,
//         1,
//         1,
//         1
//      ],
//      [
//         0,
//         0,
//         0,
//         0,
//         0
//      ],
//      [
//         2,
//         2,
//         2,
//         2,
//         2
//      ],
//      [
//         0,
//         1,
//         2,
//         1,
//         0
//      ],
//      [
//         2,
//         1,
//         0,
//         1,
//         2
//      ],
//      [
//         0,
//         0,
//         1,
//         0,
//         0
//      ],
//      [
//         2,
//         2,
//         1,
//         2,
//         2
//      ],
//      [
//         1,
//         2,
//         2,
//         2,
//         1
//      ],
//      [
//         1,
//         0,
//         0,
//         0,
//         1
//      ],
//      [
//         1,
//         0,
//         1,
//         0,
//         1
//      ],
//      [
//         1,
//         2,
//         1,
//         2,
//         1
//      ],
//      [
//         0,
//         1,
//         0,
//         1,
//         0
//      ],
//      [
//         2,
//         1,
//         2,
//         1,
//         2
//      ],
//      [
//         1,
//         1,
//         0,
//         1,
//         1
//      ],
//      [
//         1,
//         1,
//         2,
//         1,
//         1
//      ],
//      [
//         0,
//         1,
//         1,
//         1,
//         0
//      ],
//      [
//         2,
//         1,
//         1,
//         1,
//         2
//      ],
//      [
//         0,
//         2,
//         0,
//         2,
//         0
//      ],
//      [
//         2,
//         0,
//         2,
//         0,
//         2
//      ],
//      [
//         2,
//         0,
//         1,
//         2,
//         0
//      ]
//   ],
//   "linesCount":[
//      1,
//      5,
//      15,
//      20
//   ],
//   "bets":[
//      0.1,
//      0.25,
//      0.5,
//      0.75,
//      1
//   ],
//   "bonus":{
//     "type":"tap",
//     "isEnabled":true,
//     "noOfItem":5,
//     "payOut":[
//         50,
//         40,
//         30,
//         20,
//         0
//     ],
//     "payOutProb":[
        
//     ]
//    },
//   "gamble":{
//      "type":"card",
//      "isEnabled":false
//   },
//   "Symbols":[
//      {
//         "Name":"0",
//         "Id":0,
//         "reelInstance":{
//            "0":9,
//            "1":9,
//            "2":9,
//            "3":9,
//            "4":9
//         },
//         "useWildSub":true,
//         "multiplier":[
//            [
//               100,
//               0
//            ],
//            [
//               40,
//               0
//            ],
//            [
//               20,
//               0
//            ]
//         ]
//      },
//      {
//         "Name":"1",
//         "Id":1,
//         "reelInstance":{
//            "0":9,
//            "1":9,
//            "2":9,
//            "3":9,
//            "4":9
//         },
//         "useWildSub":true,
//         "multiplier":[
//            [
//               100,
//               0
//            ],
//            [
//               40,
//               0
//            ],
//            [
//               20,
//               0
//            ]
//         ]
//      },
//      {
//         "Name":"2",
//         "Id":2,
//         "reelInstance":{
//            "0":9,
//            "1":9,
//            "2":9,
//            "3":9,
//            "4":9
//         },
//         "useWildSub":true,
//         "multiplier":[
//            [
//               100,
//               0
//            ],
//            [
//               40,
//               0
//            ],
//            [
//               20,
//               0
//            ]
//         ]
//      },
//      {
//         "Name":"3",
//         "Id":3,
//         "reelInstance":{
//            "0":9,
//            "1":9,
//            "2":9,
//            "3":9,
//            "4":9
//         },
//         "useWildSub":true,
//         "multiplier":[
//            [
//               100,
//               0
//            ],
//            [
//               40,
//               0
//            ],
//            [
//               20,
//               0
//            ]
//         ]
//      },
//      {
//         "Name":"4",
//         "Id":4,
//         "reelInstance":{
//            "0":9,
//            "1":9,
//            "2":9,
//            "3":9,
//            "4":9
//         },
//         "useWildSub":true,
//         "multiplier":[
//            [
//               100,
//               0
//            ],
//            [
//               40,
//               0
//            ],
//            [
//               20,
//               0
//            ]
//         ]
//      },
//      {
//         "Name":"5",
//         "Id":5,
//         "reelInstance":{
//            "0":5,
//            "1":5,
//            "2":5,
//            "3":5,
//            "4":5
//         },
//         "useWildSub":true,
//         "multiplier":[
//            [
//               150,
//               0
//            ],
//            [
//               75,
//               0
//            ],
//            [
//               40,
//               0
//            ]
//         ]
//      },
//      {
//         "Name":"6",
//         "Id":6,
//         "reelInstance":{
//            "0":5,
//            "1":5,
//            "2":5,
//            "3":5,
//            "4":5
//         },
//         "useWildSub":true,
//         "multiplier":[
//            [
//               150,
//               0
//            ],
//            [
//               75,
//               0
//            ],
//            [
//               40,
//               0
//            ]
//         ]
//      },
//      {
//         "Name":"7",
//         "Id":7,
//         "reelInstance":{
//            "0":5,
//            "1":5,
//            "2":5,
//            "3":5,
//            "4":5
//         },
//         "useWildSub":true,
//         "multiplier":[
//            [
//               150,
//               0
//            ],
//            [
//               75,
//               0
//            ],
//            [
//               40,
//               0
//            ]
//         ]
//      },
//      {
//         "Name":"8",
//         "Id":8,
//         "reelInstance":{
//            "0":5,
//            "1":5,
//            "2":5,
//            "3":5,
//            "4":5
//         },
//         "useWildSub":true,
//         "multiplier":[
//            [
//               150,
//               0
//            ],
//            [
//               75,
//               0
//            ],
//            [
//               40,
//               0
//            ]
//         ]
//      },
//      {
//         "Name":"Wild",
//         "Id":9,
//         "reelInstance":{
//            "0":2,
//            "1":2,
//            "2":2,
//            "3":2,
//            "4":2
//         },
//         "description":"Substitutes for all symbols except Scatter.",
//         "useWildSub":false,
//         "multiplier":[
           
//         ]
//      },
//      {
//         "Name":"Scatter",
//         "Id":10,
//         "reelInstance":{
//            "0":5,
//            "1":5,
//            "2":5,
//            "3":5,
//            "4":5
//         },
//         "description":"Scatter: Offers higher pay outs when 4 or more symbols appear anywhere on the result matrix. Payout: 5x - 500, 4x - 200",
//         "useWildSub":false,
//         "multiplier":[
//            [
//               500,
//               0
//            ],
//            [
//               250,
//               0
//            ],
//            [
//             100,
//             0
//            ]
//         ]
//      }
//   ]
// }
// {
//   "id":"SL-CLEO",
//   "matrix":{
//      "x":5,
//      "y":3
//   },
//   "linesApiData":[
//      [
//         1,
//         1,
//         1,
//         1,
//         1
//      ],
//      [
//         0,
//         0,
//         0,
//         0,
//         0
//      ],
//      [
//         2,
//         2,
//         2,
//         2,
//         2
//      ],
//      [
//         0,
//         1,
//         2,
//         1,
//         0
//      ],
//      [
//         2,
//         1,
//         0,
//         1,
//         2
//      ],
//      [
//         0,
//         0,
//         1,
//         2,
//         2
//      ],
//      [
//         2,
//         2,
//         1,
//         0,
//         0
//      ],
//      [
//         1,
//         0,
//         1,
//         2,
//         1
//      ],
//      [
//         1,
//         2,
//         1,
//         0,
//         1
//      ],
//      [
//         0,
//         1,
//         1,
//         1,
//         2
//      ],
//      [
//         2,
//         1,
//         1,
//         1,
//         0
//      ],
//      [
//         1,
//         0,
//         0,
//         1,
//         2
//      ],
//      [
//         1,
//         2,
//         2,
//         1,
//         0
//      ],
//      [
//         1,
//         1,
//         0,
//         1,
//         2
//      ],
//      [
//         1,
//         1,
//         2,
//         1,
//         0
//      ],
//      [
//         0,
//         0,
//         1,
//         2,
//         1
//      ],
//      [
//         2,
//         2,
//         1,
//         0,
//         1
//      ],
//      [
//         1,
//         0,
//         1,
//         2,
//         2
//      ],
//      [
//         1,
//         2,
//         1,
//         0,
//         0
//      ],
//      [
//         0,
//         0,
//         0,
//         1,
//         2
//      ]
//   ],
//   "linesCount":[
//      1,
//      5,
//      15,
//      20
//   ],
//   "bets":[
//      0.01,
//      0.02,
//      0.05,
//      0.1,
//      0.25,
//      0.5,
//      0.75,
//      1,
//      1.25,
//      1.5,
//      1.75,
//      2,
//      2.5,
//      3,
//      3.5,
//      4
//   ],
//   "bonus": {
//   "type": "spin",
//   "isEnabled": false,
//   "noOfItem": 8,
//   "payOut": [200, 100, 70, 50, 30, 20, 10, 5],
//   "payOutProb": [0.05, 0.5, 1, 3, 10, 20, 25, 39.4]
// },
//   "gamble":{
//      "type":"card",
//      "isEnabled":false
//   },
//   "Symbols":[
//      {
//         "Name":"0",
//         "Id":0,
//         "reelInstance":{
//            "0":10,
//            "1":10,
//            "2":10,
//            "3":10,
//            "4":10
//         },
//         "useWildSub":true,
//         "multiplier":[
//            [
//               100,
//               0
//            ],
//            [
//               25,
//               0
//            ],
//            [
//               5,
//               0
//            ]
//         ]
//      },
//      {
//         "Name":"1",
//         "Id":1,
//         "reelInstance":{
//            "0":10,
//            "1":10,
//            "2":10,
//            "3":10,
//            "4":10
//         },
//         "useWildSub":true,
//         "multiplier":[
//            [
//               100,
//               0
//            ],
//            [
//               25,
//               0
//            ],
//            [
//               5,
//               0
//            ]
//         ]
//      },
//      {
//         "Name":"2",
//         "Id":2,
//         "reelInstance":{
//            "0":10,
//            "1":10,
//            "2":10,
//            "3":10,
//            "4":10
//         },
//         "useWildSub":true,
//         "multiplier":[
//            [
//               100,
//               0
//            ],
//            [
//               25,
//               0
//            ],
//            [
//               5,
//               0
//            ]
//         ]
//      },
//      {
//         "Name":"3",
//         "Id":3,
//         "reelInstance":{
//            "0":10,
//            "1":10,
//            "2":10,
//            "3":10,
//            "4":10
//         },
//         "useWildSub":true,
//         "multiplier":[
//            [
//               100,
//               0
//            ],
//            [
//               25,
//               0
//            ],
//            [
//               5,
//               0
//            ]
//         ]
//      },
//      {
//         "Name":"4",
//         "Id":4,
//         "reelInstance":{
//            "0":10,
//            "1":10,
//            "2":10,
//            "3":10,
//            "4":10
//         },
//         "useWildSub":true,
//         "multiplier":[
//            [
//               100,
//               0
//            ],
//            [
//               50,
//               0
//            ],
//            [
//               5,
//               0
//            ]
//         ]
//      },
//      {
//         "Name":"5",
//         "Id":5,
//         "reelInstance":{
//            "0":10,
//            "1":10,
//            "2":10,
//            "3":10,
//            "4":10
//         },
//         "useWildSub":true,
//         "multiplier":[
//            [
//               125,
//               0
//            ],
//            [
//               50,
//               0
//            ],
//            [
//               10,
//               0
//            ]
//         ]
//      },
//      {
//         "Name":"6",
//         "Id":6,
//         "reelInstance":{
//            "0":4,
//            "1":4,
//            "2":4,
//            "3":4,
//            "4":4
//         },
//         "useWildSub":true,
//         "multiplier":[
//            [
//               250,
//               0
//            ],
//            [
//               50,
//               0
//            ],
//            [
//               10,
//               0
//            ]
//         ]
//      },
//      {
//         "Name":"7",
//         "Id":7,
//         "reelInstance":{
//            "0":4,
//            "1":4,
//            "2":4,
//            "3":4,
//            "4":4
//         },
//         "useWildSub":true,
//         "multiplier":[
//            [
//               250,
//               0
//            ],
//            [
//               75,
//               0
//            ],
//            [
//               10,
//               0
//            ]
//         ]
//      },
//      {
//         "Name":"8",
//         "Id":8,
//         "reelInstance":{
//            "0":4,
//            "1":4,
//            "2":4,
//            "3":4,
//            "4":4
//         },
//         "useWildSub":true,
//         "multiplier":[
//            [
//               400,
//               0
//            ],
//            [
//               100,
//               0
//            ],
//            [
//               15,
//               0
//            ]
//         ]
//      },
//      {
//         "Name":"9",
//         "Id":9,
//         "reelInstance":{
//            "0":4,
//            "1":4,
//            "2":4,
//            "3":4,
//            "4":4
//         },
//         "useWildSub":true,
//         "multiplier":[
//            [
//               750,
//               0
//            ],
//            [
//               100,
//               0
//            ],
//            [
//               25,
//               0
//            ]
//         ]
//      },
//      {
//         "Name":"Wild",
//         "Id":10,
//         "reelInstance":{
//            "0":5,
//            "1":5,
//            "2":5,
//            "3":5,
//            "4":5
//         },
//         "description":"Substitutes for all symbols except Jackpot, Free Spin, Bonus, and Scatter.",
//         "useWildSub":false,
//         "multiplier":[
           
//         ]
//      },
//      {
//         "Name":"FreeSpin",
//         "Id":11,
//         "reelInstance":{
//            "0":8,
//            "1":8,
//            "2":8,
//            "3":8,
//            "4":8
//         },
//         "description":"Activates 3, 5, or 10 free spins when 3, 4, or 5 symbols appear anywhere on the result matrix.",
//         "useWildSub":false,
//         "multiplier":[
//            [
//               0,
//               10
//            ],
//            [
//               0,
//               5
//            ],
//            [
//               0,
//               3
//            ]
//         ]
//      },
//      {
//         "Name":"Jackpot",
//         "Id":12,
//         "reelInstance":{
//            "0":1,
//            "1":1,
//            "2":1,
//            "3":1,
//            "4":1
//         },
//         "description":"Mega win triggered by 5 Jackpot symbols appearing anywhere on the result matrix. Payout: 5000x",
//         "useWildSub":false,
//         "multiplier":[
           
//         ],
//         "defaultAmount":5000,
//         "symbolsCount":5,
//         "increaseValue":5
//      }
//   ]
// }
{
   id: "SL-PM",
   matrix: {
     x: 5,
     y: 3,
   },
   linesApiData: [
     [1, 1, 1, 1, 1],
     [0, 0, 0, 0, 0],
     [2, 2, 2, 2, 2],
     [0, 1, 2, 1, 0],
     [2, 1, 0, 1, 2],
     [1, 0, 1, 2, 1],
     [1, 2, 1, 0, 1],
     [0, 0, 1, 2, 2],
     [2, 2, 1, 0, 0],
     [0, 1, 0, 1, 0],
     [2, 1, 2, 1, 2],
     [1, 0, 0, 0, 1],
     [1, 2, 2, 2, 1],
     [0, 1, 1, 1, 0],
     [2, 1, 1, 1, 2],
     [1, 1, 0, 1, 1],
     [1, 1, 2, 1, 1],
     [0, 2, 0, 2, 0],
     [2, 0, 2, 0, 2],
     [2, 0, 1, 0, 2],
     [0, 2, 1, 2, 0],
     [0, 2, 2, 2, 0],
     [2, 0, 0, 0, 2],
     [1, 0, 2, 0, 1],
     [1, 2, 0, 2, 1],
   ],
   bets: [0.1, 0.25, 0.5, 0.75, 1],
   freeSpinData : [[4,3],[5,5,],[6,7],[7,10],[8,25]],
   Symbols: [
     {
       Name: "0",
       Id: 0,
       reelInstance: {
         "0": 9,
         "1": 9,
         "2": 9,
         "3": 9,
         "4": 9,
       },
       useWildSub: true,
       multiplier: [
         [100, 0],
         [50, 0],
         [25, 0],
       ],
     },
     {
       Name: "1",
       Id: 1,
       reelInstance: {
         "0": 9,
         "1": 9,
         "2": 9,
         "3": 9,
         "4": 9,
       },
       useWildSub: true,
       multiplier: [
         [100, 0],
         [50, 0],
         [25, 0],
       ],
     },
     {
       Name: "2",
       Id: 2,
       reelInstance: {
         "0": 9,
         "1": 9,
         "2": 9,
         "3": 9,
         "4": 9,
       },
       useWildSub: true,
       multiplier: [
         [100, 0],
         [50, 0],
         [25, 0],
       ],
     },
     {
       Name: "3",
       Id: 3,
       reelInstance: {
         "0": 9,
         "1": 9,
         "2": 9,
         "3": 9,
         "4": 9,
       },
       useWildSub: true,
       multiplier: [
         [100, 0],
         [50, 0],
         [25, 0],
       ],
     },
     {
       Name: "4",
       Id: 4,
       reelInstance: {
         "0": 9,
         "1": 9,
         "2": 9,
         "3": 9,
         "4": 9,
       },
       useWildSub: true,
       multiplier: [
         [100, 0],
         [50, 0],
         [25, 0],
       ],
     },
     {
       Name: "5",
       Id: 5,
       reelInstance: {
         "0": 9,
         "1": 9,
         "2": 9,
         "3": 9,
         "4": 9,
       },
       useWildSub: true,
       multiplier: [
         [100, 0],
         [50, 0],
         [25, 0],
       ],
     },
     {
       Name: "6",
       Id: 6,
       reelInstance: {
         "0": 9,
         "1": 9,
         "2": 9,
         "3": 9,
         "4": 9,
       },
       useWildSub: true,
       multiplier: [
         [100, 0],
         [50, 0],
         [25, 0],
       ],
     },
     {
       Name: "7",
       Id: 7,
       reelInstance: {
         "0": 9,
         "1": 9,
         "2": 9,
         "3": 9,
         "4": 9,
       },
       useWildSub: true,
       multiplier: [
         [100, 0],
         [50, 0],
         [25, 0],
       ],
     },
     {
       Name: "8",
       Id: 8,
       reelInstance: {
         "0": 4,
         "1": 4,
         "2": 4,
         "3": 4,
         "4": 4,
       },
       useWildSub: true,
       multiplier: [
         [200, 0],
         [80, 0],
         [40, 0],
       ],
     },
     {
       Name: "9",
       Id: 9,
       reelInstance: {
         "0": 4,
         "1": 4,
         "2": 4,
         "3": 4,
         "4": 4,
       },
       useWildSub: true,
       multiplier: [
         [200, 0],
         [80, 0],
         [40, 0],
       ],
     },
     {
       Name: "10",
       Id: 10,
       reelInstance: {
         "0": 4,
         "1": 4,
         "2": 4,
         "3": 4,
         "4": 4,
       },
       useWildSub: true,
       multiplier: [
         [200, 0],
         [80, 0],
         [40, 0],
       ],
     },
     {
       Name: "11",
       Id: 11,
       reelInstance: {
         "0": 4,
         "1": 4,
         "2": 4,
         "3": 4,
         "4": 4,
       },
       useWildSub: true,
       multiplier: [
         [200, 0],
         [80, 0],
         [40, 0],
       ],
     },
     {
       Name: "Wild",
       Id: 12,
       reelInstance: {
         "0": 20,
         "1": 20,
         "2": 20,
         "3": 20,
         "4": 20,
       },
       description:
         "Substitutes for all symbols except Jackpot, Free Spin, Bonus, and Scatter.",
       useWildSub: false,
       multiplier: [],
     },
     {
       Name: "Jackpot",
       Id: 13,
       reelInstance: {
         "0": 1,
         "1": 1,
         "2": 1,
         "3": 1,
         "4": 1,
       },
       description:
         "Mega win triggered by 5 Jackpot symbols appearing anywhere on the result matrix. Payout: 5000x",
       useWildSub: false,
       multiplier: [],
       defaultAmount: 5000,
       symbolsCount: 5,
       increaseValue: 5,
     },
   ],
 }
]
