export const gameData = [
  {
    id: "SL-PM",
    matrix: {
      x: 5,
      y: 3,
    },
    linesApiData: [
      [1, 1, 1, 1, 1],
      [0, 0, 0, 0, 0],
      [2, 2, 2, 2, 2],
      [0, 1, 2, 1, 0],
      [2, 1, 0, 1, 2],
      [1, 0, 1, 2, 1],
      [1, 2, 1, 0, 1],
      [0, 0, 1, 2, 2],
      [2, 2, 1, 0, 0],
      [0, 1, 0, 1, 0],
      [2, 1, 2, 1, 2],
      [1, 0, 0, 0, 1],
      [1, 2, 2, 2, 1],
      [0, 1, 1, 1, 0],
      [2, 1, 1, 1, 2],
      [1, 1, 0, 1, 1],
      [1, 1, 2, 1, 1],
      [2, 0, 2, 0, 2],
      [0, 2, 0, 2, 0],
      [2, 0, 1, 0, 2],
      [0, 2, 1, 2, 0],
      [0, 2, 2, 2, 0],
      [2, 0, 0, 0, 2],
      [1, 0, 2, 0, 1],
      [1, 2, 0, 2, 1],
    ],
    linesCount: [1, 5, 15, 20, 25],
    bets: [1, 5, 15, 20],
    bonus: {
      type: "tap",
      isEnabled: false,
      noOfItem: 8,
      payOut: [1200, 200, 100, 50, 25, 10, 3, 0],
      payOutProb: [0.2, 0.6, 1.2, 2, 4, 20, 48, 20],
    },
    gamble: {
      type: "card",
      isEnabled: false,
    },
    Symbols: [
      {
        Name: "0",
        Id: 0,
        reelInstance: {
          "0": 9,
          "1": 9,
          "2": 9,
          "3": 9,
          "4": 9,
        },
        useWildSub: true,
        multiplier: [
          [20, 0],
          [10, 0],
          [5, 0],
        ],
      },
      {
        Name: "1",
        Id: 1,
        reelInstance: {
          "0": 9,
          "1": 9,
          "2": 9,
          "3": 9,
          "4": 9,
        },
        useWildSub: true,
        multiplier: [
          [20, 0],
          [10, 0],
          [5, 0],
        ],
      },
      {
        Name: "2",
        Id: 2,
        reelInstance: {
          "0": 9,
          "1": 9,
          "2": 9,
          "3": 9,
          "4": 9,
        },
        useWildSub: true,
        multiplier: [
          [20, 0],
          [10, 0],
          [5, 0],
        ],
      },
      {
        Name: "3",
        Id: 3,
        reelInstance: {
          "0": 9,
          "1": 9,
          "2": 9,
          "3": 9,
          "4": 9,
        },
        useWildSub: true,
        multiplier: [
          [20, 0],
          [10, 0],
          [5, 0],
        ],
      },
      {
        Name: "4",
        Id: 4,
        reelInstance: {
          "0": 9,
          "1": 9,
          "2": 9,
          "3": 9,
          "4": 9,
        },
        useWildSub: true,
        multiplier: [
          [20, 0],
          [10, 0],
          [5, 0],
        ],
      },
      {
        Name: "5",
        Id: 5,
        reelInstance: {
          "0": 4,
          "1": 4,
          "2": 4,
          "3": 4,
          "4": 4,
        },
        useWildSub: true,
        multiplier: [
          [30, 0],
          [20, 0],
          [10, 0],
        ],
      },
      {
        Name: "6",
        Id: 6,
        reelInstance: {
          "0": 4,
          "1": 4,
          "2": 4,
          "3": 4,
          "4": 4,
        },
        useWildSub: true,
        multiplier: [
          [30, 0],
          [20, 0],
          [10, 0],
        ],
      },
      {
        Name: "7",
        Id: 7,
        reelInstance: {
          "0": 4,
          "1": 4,
          "2": 4,
          "3": 4,
          "4": 4,
        },
        useWildSub: true,
        multiplier: [
          [30, 0],
          [20, 0],
          [10, 0],
        ],
      },
      {
        Name: "8",
        Id: 8,
        reelInstance: {
          "0": 4,
          "1": 4,
          "2": 4,
          "3": 4,
          "4": 4,
        },
        useWildSub: true,
        multiplier: [
          [30, 0],
          [20, 0],
          [10, 0],
        ],
      },
      {
        Name: "9",
        Id: 9,
        reelInstance: {
          "0": 5,
          "1": 4,
          "2": 5,
          "3": 3,
          "4": 5,
        },
        useWildSub: false,
        multiplier: [
          [0, 25],
          [0, 15],
          [0, 5],
        ],
      },
      {
        Name: "10",
        Id: 10,
        reelInstance: {
          "0": 5,
          "1": 4,
          "2": 5,
          "3": 3,
          "4": 5,
        },
        useWildSub: false,
        multiplier: [
          [0, 25],
          [0, 15],
          [0, 5],
        ],
      },
      {
        Name: "Wild",
        Id: 12,
        reelInstance: {
          "0": 0,
          "1": 2,
          "2": 2,
          "3": 2,
          "4": 2,
        },
        useWildSub: false,
        multiplier: [],
      },
      {
        Name: "11",
        Id: 11,
        reelInstance: {
          "0": 2,
          "1": 2,
          "2": 3,
          "3": 2,
          "4": 2,
        },
        useWildSub: false,
        multiplier: [
          [300, 0],
          [100, 0],
          [30, 0],
        ],
        freeSpin: 10,
        count: 5,
      },
      {
        Name: "Jackpot",
        Id: 13,
        reelInstance: {
          "0": 2,
          "1": 2,
          "2": 2,
          "3": 2,
          "4": 2,
        },
        useWildSub: false,
        multiplier: [],
        defaultAmount: 12000,
        symbolsCount: 5,
        increaseValue: 5,
      },
    ],
  }
];
